# Generated by Django 3.2.12 on 2022-03-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_field', models.CharField(max_length=200)),
                ('from_field', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('subjet', models.CharField(max_length=200)),
                ('message_id', models.CharField(max_length=200)),
            ],
        ),
    ]
