# Generated by Django 3.2.12 on 2022-03-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='subjet',
            new_name='subject',
        ),
    ]
